### ISSUE TITLE
Bug with Clipboard

### ISSUE THREAD

**Issue by vars1ty** [veeenu/hudhook#121]
Currently I've got a multi-line editor built-in into my cheat so that people can write script code using Rune.
Although one issue that keeps coming up is the fact that the clipboard is broken. It works for the first few times, then it's unable to:
- Capture (and Copy) any new data
- Paste in any data
- Mark all content using CTRL + A

Is there a workaround for this? Tried if it happens on native Windows with MSVC, and it's the same story there.

**Comment by veeenu** [comment]
`hudhook` doesn't _directly_ manage the clipboard, and I'm not confident `imgui` does either.

According to the [`imgui` crate examples](https://github.com/imgui-rs/imgui-rs/blob/main/imgui-examples/examples/support/clipboard.rs), it looks like there is an implementable [trait](https://docs.rs/imgui/latest/imgui/trait.ClipboardBackend.html) for clipboard operations that has to be [manually set](https://docs.rs/imgui/latest/imgui/struct.Context.html#method.set_clipboard_backend) on the context at initialization.

I believe copying and pasting (hehe) the example above should be enough to make things work. If you already have something similar in place, then there may be an actual bug in the implementation of the input management system.

Could you please build a minimum reproducible example against one of the [sample hosts](https://github.com/veeenu/hudhook/tree/main/examples) (ideally the one your target game uses)?

I have a hunch that the game itself could be trying to interact with the clipboard and thus disrupt the flow of the overlay. If that's the case -- and thus the issue is not reproducible against the sample hosts -- then it might be worth it to implement a super aggressive clipboard manager that tries to repeatedly overwrite the clipboard over the course of a few frames.
