### ISSUE TITLE
Build failed on --target i686-pc-windows-msvc

### ISSUE THREAD

**Issue by bub-bl** [veeenu/hudhook#128]
I can't build from the target `i686-pc-windows-msvc`. The target `x86_64-pc-windows-msvc` works fine.

**Comment by veeenu** [comment]
Could you provide more details, please? I don't have a i686 build pipeline setup at the moment.

**Comment by bub-bl** [comment]
A lot of errors come from varius crates. I can't post the logs because she is pretty insanly big.
I have tested with a blank project and im only useing hudhook + imgui_hook but a got the same problem.

I think the majority of the problem come from the winapi crate. Maybe replace it with windows-sys for better compatibility ?? (the api is almost the same).

Another things is the size of produced .dll, i reach 600 ko's on a blank project dll when i build with hudhook crate. (The problem come from the size of imgui-sys crate).

**Comment by veeenu** [comment]
`hudhook` hasn't depended on the `winapi` crate in a long, long time, and we actually adopted `windows` pretty early.

I found out that we still transitively depend on it via `tracing-subscriber` but that's only actually activated on the examples and tests, so it shouldn't influence regular usage.

Turns out there was an actual issue on i686 but it should be covered by #129, and it only produced two errors.

Your error messages refer to missing standard traits and types:

```
error[E0412]: cannot find type `Option` in this scope
    --> C:\Users\bubbl\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\macros.rs:412:26
     |
412  |           pub type $func = Option<unsafe extern "system" fn($($p: $t,)*) -> $ret>;
     |                            ^^^^^^ not found in this scope
error[E0405]: cannot find trait `Clone` in this scope
   --> C:\Users\bubbl\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winapi-0.3.9\src\macros.rs:393:14
    |
393 |           impl Clone for $name {
    |                ^^^^^ not found in this scope
```

This makes me think you might actually be missing the target triple entirely, as that's what it looks like in these cases. It could be that you have it installed but only on a different toolchain -- e.g. you're compiling with nightly but have it installed on stable or viceversa. Try this:

```
rustup target add i686-pc-windows-msvc --toolchain stable
rustup target add i686-pc-windows-msvc --toolchain nightly
```

**Comment by veeenu** [comment]
Closing this and tracking the `no_std` support efforts in #131
