### ISSUE TITLE
DX9 Hook non-functioning

### ISSUE THREAD

**Issue by vars1ty** [veeenu/hudhook#132]
The DirectX 9 hook crashes when I try to use it, it apparently calls `drop()` for whatever reason when not even supposed to?
It used not to happen around 3 months ago, although back then the entire UI was unresponsive, all compiled with `i686-pc-windows-msvc`.

The game can be downloaded from [here](https://archive.org/download/star-stable-win-iso-en.-cz.-fi.-hu.-de.-no.-se_202011/Star_Stable_Win_ISO_EN.CZ.FI.HU.DE.NO.SE.zip) and is an older RPG game.
Hook code is nothing special, it's the one from examples. The error message that shows up is shown in the picture below (ignore the broken colors, it's wine).

![image](https://github.com/veeenu/hudhook/assets/54314240/09458493-69a6-4390-bdf2-b63a008711e3)

**Comment by veeenu** [comment]
Can you elaborate on "calls `drop()` for whatever reason when not even supposed to"? How confident are you that that statement is correct?

That `drop` implementation at the panic call site is **very** intentional, as the entire point of `DummyHwnd` is to be a RAII guard.

The panic message is happening on a call to `UnregisterClass` right after `DestroyWindow`, and it states that there is a window of the specified class still open. In other words, either `DestroyWindow` did not work, or the assumption that it is synchronous is wrong and should be correctly managed.

You mention you are running wine; perhaps their implementation diverges ever so slightly from Windows' that some assumptions can't be relied upon?

Another option is that there are two `DummyHwnd` that get created for some reason and the class can't get unregistered during a drop because the other instance is still active, but I don't see a path for that to happen really unless the game is doing some freaky stuff.

I can look into it soonish. I have little experience with DX9 specifically, but I don't think that's the culprit here. I also don't have a Linux machine with wine available, so I'll have to test on Windows 11.

**Comment by vars1ty** [comment]
Not very confident, but it's the only place where I could find the code it's getting an error at.
Also, I had a friend test it on Windows and it crashed there as well with the example hook.
