### ISSUE TITLE
Unable to interact with UI

### ISSUE THREAD

**Issue by BSFishy** [veeenu/hudhook#26]
Not sure if it's an issue on my end or not, but I can't seem to find a way to actually interact with the UI. I can't move or resize the window, and I set up a little demo with a render function that looks something like this:

```rust
ctx.frame.text(format!("Hello, hello, {:?}!", name));
if ctx.frame.button(im_str!("click"), [30., 30.]) {
    info!("CLICKED");
}
```

Which I can see both the text and the button, but when I click the button, I don't get anything in my logs. If it's any help, the game I'm trying to hook into is [Escape the Backrooms](https://store.steampowered.com/app/1943950/Escape_the_Backrooms/).

Here are the other two functions too just in case:

```rust
fn is_visible(&self) -> bool {
    true
}

fn is_capturing(&self) -> bool {
    true
}
```

**Comment by veeenu** [comment]
Hi! Are you by chance using the latest version published on `crates.io`? It's been quite a long time since I published a release, try using the last commit of this repo!

**Comment by BSFishy** [comment]
Alright, I switched to point to git instead of `crates.io`, but I was using the `base_address` function, that doesn't seem to be there anymore. What should I use instead of that?

Also, I'm curious as to why you're not uploading new releases to `crates.io`?

**Comment by veeenu** [comment]
Right up until maybe a month or two ago, the code was very unpolished and the repo was tightly coupled to the Dark Souls III and Elden Ring practice tools, plus there are a lot of `path = ...` dependencies from the `imgui-*` renderers I still did not get around to addressing. Debating whether I should release the `imgui-*` crates on crates.io: they have not been tested for other use cases and I'm not planning to maintain them for other use cases, otoh the crate separation is very useful as I can test the renderers in isolation. crates.io does not allow relative path dependencies inside of a workspace so the superior solution of just cloaking these crates and release `hudhook` only is not viable.

That said, I do think it is high time for a new crates.io release as the library is seeing a reasonable amount of activity lately, plus the code is stable enough to warrant that. Once this problem is solved, hopefully soon, I think that can definitely happen.

To answer your question: `base_address` was removed as being out of scope, you can get the same effect by calling `GetModuleHandleA(null)` [directly](https://veeenu.github.io/hudhook/src/hudhook/memory/process_util.rs.html#12).

**Comment by thompsondt** [comment]
For whatever it's worth, I'm considering using this with a different GUI framework. I support the decoupling.
